# SPDX-FileCopyrightText: 2025 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Check existence of Headscale systemd service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{ headscale_identifier }}.service"
  register: headscale_service_stat

- name: Uninstall Headscale systemd services and files
  when: headscale_service_stat.stat.exists | bool
  block:
    - name: Ensure Headscale systemd service is stopped
      ansible.builtin.service:
        name: "{{ headscale_identifier }}"
        state: stopped
        enabled: false
        daemon_reload: true

    - name: Ensure Headscale systemd service does not exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/{{ headscale_identifier }}.service"
        state: absent

    - name: Ensure Headscale container network does not exist via community.docker.docker_network
      when: devture_systemd_docker_base_container_network_creation_method == 'ansible-module'
      community.docker.docker_network:
        name: "{{ headscale_container_network }}"
        state: absent

    - name: Ensure Headscale container network does not exist via ansible.builtin.command
      when: devture_systemd_docker_base_container_network_creation_method == 'command'
      ansible.builtin.command:
        cmd: >-
          {{ devture_systemd_docker_base_host_command_docker }} network rm
          {{ headscale_container_network }}
      register: network_deletion_result
      changed_when: headscale_container_network in network_deletion_result.stdout

    - name: Ensure Headscale path does not exist
      ansible.builtin.file:
        path: "{{ headscale_base_path }}"
        state: absent
